### ISSUE TITLE
#1 interface Menu 접근 제한자 문제

### ISSUE THREAD

**Issue by lynring24** [snowflake-1117/AssistantManager#1]
### 문제 
interface를 사용할 경우, printMenu()의 접근 제한자를 public, abstract, default 등으로만 설정할 수 있습니다.  따라서, 디자인이 조금 변경되어야 할 것 같습니다.
> Illegal modifier for the interface method; only public, abstract, default, static and strictfp are permitted.

###  방안1 
```
abstract class Menu {
	abstract  public void showAndSelect();
	abstract  protected void printMenu();
}
```
```
public class  YourManager extends Menu{
	@Override
	public void showAndSelect() {}
	@Override
	protected void printMenu() {}
}
```
interface 대신 abstract class로 변경하고, printMenu의 접근 제한자를 protected으로 변경하는 방법

###  방안2
@charis227 님의 의견대로 private을 유지하고 Menu에서 제외
(다만, 기능이 중복된 다는 점이 걸립니다. )

**Comment by jiunoh** [comment]
프린트 네 줄 출력하는 함수를 위해 상속과 오버라이드까지 진행할 필요는 없다고 (여전히) 생각하는 바입니다....

**Comment by lynring24** [comment]
인터페이스가 Illegal modifier for the interface method; only public, abstract, default, static and strictfp are permitted. 라는 이유로 protected 를 제한자로 쓸 수 없습니다

**Comment by snowflake-1117** [comment]
abstract 클래스 자체가 미구현함수+구현함수를 같이 쓰려는 의도를 가지고 있기 때문에 함수 두 가지를 모두 미구현 함수로 둘 거면 printMenu를 default로 사용하는 게 나을듯합니다.

이러면 public이 아니니 일단 안썼어도 괜찮을거라고 생각되네요. 구조를 너무 바꾸면 감점요소가 있다고했으니까 되도록 어쩔수 없는 경우애만 바꾸는게 나을 것 같아요! 다른 부분에서 충분히 변경사항이 발생할 수 있으니까요!

**Comment by lynring24** [comment]
1. abstact class로 변경해뒀습니다.
2. 제가 임시로 AssistantManager의 초기 포맷을 잡아뒀습니다. 이에 맞춰 작업해주시면 됩니다.
