### ISSUE TITLE
[Develop] Account 브랜치를 develop 브랜치에 merge 했습니다.

### ISSUE THREAD

**Issue by snowflake-1117** [snowflake-1117/AssistantManager#11]
AssistantManager의 충돌 부분 역시 해결했습니다. Memo 브랜치를 merge하면 구현이 완료될 듯 합니다.

**Comment by lynring24** [comment]
확인 했습니다. Account 기능도 버그를 잡아 업데이트를 했으니 풀 리퀘를 확인해주세요.
