### ISSUE TITLE
파일 이름에 대해

### ISSUE THREAD

**Issue by jiunoh** [snowflake-1117/AssistantManager#3]
메모/가계부의 경우 파일 입출력으로 저장하기 때문에 파일이 필요한데,
해당 파일의 이름 양식을 통일하는 편이 낫다고 생각합니다. 
메모는 임시로 memoManager.txt로 해놨지만 조율하는 게 좋겠습니다.

**Comment by lynring24** [comment]
저는 'Account.txt'로 사용하는데, 사실 파일이 드러나는 게 아니기 때문에 상관없지 않을까요?
