### ISSUE TITLE
메모 기능 일차적으로 완료

### ISSUE THREAD

**Issue by jiunoh** [snowflake-1117/AssistantManager#4]
일단 개발하기로 명시된 기능은 완료된 상태지만,
혹시 다른 버그가 있을 수도 있고 머지 문제도 있기 때문에 차후에 한 번씩 테스트해주시기 바랍니다.

**Comment by snowflake-1117** [comment]
귀가 후 확인해보겠습니다!
-> 확인 완료했습니다. 잘 돌아가네요:)

**Comment by lynring24** [comment]
확인 했습니다 :)
