### ISSUE TITLE
단위변환 함수 calculateUnitConversion 의 반환값 수정에 대한 알림

### ISSUE THREAD

**Issue by snowflake-1117** [snowflake-1117/AssistantManager#5]
## 변경 전
abstract int calculateUnitConversion(boolean isConversionFromAToB);
- 함수 역할: 파라미터 입력 값에 따라 A->B 또는 B->A로 단위 변환을 한다.
- 파라미터: A단위의 값을 B단위로 변환함을 의미(true)/B단위의 값을 A단위로 변환함을 의미(false)
- 반환 값: 단위 변환의 결과 값을 리턴한다.

## 변경 후
abstract _**String**_ calculateUnitConversion(boolean isConversionFromAToB);
- 함수 역할: 파라미터 입력 값에 따라 A->B 또는 B->A로 단위 변환을 한다.
- 파라미터: A단위의 값을 B단위로 변환함을 의미(true)/B단위의 값을 A단위로 변환함을 의미(false)
- 반환 값: 단위 변환의 _**결과 값+변환단위**_ 를 문자열로 리턴한다.

**Comment by lynring24** [comment]
참고하겠습니다.
